### PR TITLE
42 initial contact page closes #42

### LINKED ISSUE #42: Initial Contact Page
Contact page is required for GDPR so that users can issue a "data subject request". A data subject request is a request made by an individual to exercise their rights under the GDPR, such as the right to access, rectify, erase, or restrict the processing of their personal data.

### PR DESCRIPTION
**Pull request by kmn6**
added contact page and footer with links to contact page and privacy policy. Added tests for footer links.

### CODE REVIEW

**Comment by kmn6** [comment]
dunno how this broke when I only changed something under console.log. Fixing.

**Comment by kmn6** [comment]
somehow I accidentally duplicated a line in the footer. Must have hit a bad keyboard shortcut or something

**Comment by jidone7061** [comment]
Approved

**Comment by kmn6** [comment]
lots of accessibility test failures

**Comment by jidone7061** [comment]
I just saw these failures in Github actions.   The initial check reflected they passed which was why I commented on approval.

**Comment by kmn6** [comment]
this site is very helpful in figuring out what the axe failures mean: https://dequeuniversity.com/rules/axe/4.6

**Comment by kmn6** [comment]
I added the Google Analytics javascript which was missing before. Is this supposed to be on every page or just the homepage?

**Pull request merged**
